name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: configure
    #   run: ./configure
    - name: install lib
      run: git clone "https://github.com/nlohmann/json.git";
           cd json;
           mkdir build;
           cd build;
           cmake ..;
           make -j4;
           make install;

    - name: Install dependencies
      run: ls;
           make;


    - name: Run test
      run: make test

    - name: Run distcheck
      run: make distcheck
