name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependences
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt-get install libgtest-dev

      
    - name: install lib
      run: git clone "https://github.com/nlohmann/json.git";
           cd json;
           mkdir build;
           cd build;
           cmake ..;
           make -j4;
           sudo make install;

    - name: make program
      run: make

    - name: Run test
      run: make test
